### PR TITLE
User Controller related pulls

### PR DESCRIPTION
**Pull request by hellosibun**
added UserEntity class inside package quora-service

### CODE REVIEW

**Comment by hellosibun** [comment]
added userAuthTokenEntity

**Comment by ashwini008** [comment]
Any reason for deleting `PasswordCryptographyProvider.java`?

**Comment by hellosibun** [comment]
> Any reason for deleting `PasswordCryptographyProvider.java`?

no no it may be deleted by mistake, i will add it again

**Review by hellosibun — COMMENTED** [review]
added exception to UserBusinessService

**Pull request merged**
